apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: snake
  janus-idp.io/tekton: snake
  backstage.io/kubernetes-id: snake
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: snake
resources:
- deployment.yaml
- route.yaml
- service.yaml
